source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'
use_frameworks!

target "OCHub" do
	pod 'OCFrame', :path => '../OCFrame'
	
	# Base
	pod 'Masonry', '1.1.0'
	pod 'IQKeyboardManager', '6.5.6'
	pod 'TMCache', '2.1.0'
	pod 'BlocksKit', '2.2.5'
	pod 'R.objc', '0.8.2'
	pod 'LSAnimator', '2.1.5'
	pod 'FontAwesomeKit', '2.2.1'
	pod 'OHHTTPStubs', '9.1.0'
	pod "ARAnalytics-JX", :subspecs => ["UMengAnalytics"], :git => 'https://github.com/tospery/ARAnalytics-JX.git'
	
	# Other
    pod 'MXParallaxHeader', '1.1.0'
	
	# pod 'MLeaksFinder', '1.0.0'
	# pod 'pop', '1.0.12'
	# pod 'SAMKeychain', '1.5.3'
	# pod 'SDCycleScrollView', '1.80'
	# pod 'TTTAttributedLabel', '2.0.0'
	# pod 'CHTCollectionViewWaterfallLayout', '0.9.8'
	# pod 'TTGTagCollectionView', '1.11.1'
	# pod 'TLYShyNavBar', '1.1.1'
	# pod 'JSBadgeView', '2.0.0'
	# pod 'LTNavigationBar', '2.1.9'
	# pod 'FDFullscreenPopGesture', '1.1'
	# pod 'AlibcTradeSDK', '4.0.0.8'
	# pod 'AliAuthSDK', '2.0.0.3'
	# pod 'mtopSDK', '3.0.0.4'
	# pod 'securityGuard', '5.4.173'
	# pod 'AliLinkPartnerSDK', '4.0.0.24'
	# pod 'BCUserTrack', '5.2.0.11-appkeys'
	# pod 'UTDID', '1.1.0.16'
	# pod 'AlipaySDK', '2.0.0-bc'
	# pod 'BuglyHotfix', '~> 2.1.0'
	# pod 'AlibcTradeSDK', '~> 3.1.1.206'
	# pod 'SDCycleScrollView', '~> 1.75'
	# pod 'MXParallaxHeader', '~> 0.6.1'
	# pod 'VBFPopFlatButton', '~> 0.0.7'
	# pod 'SVProgressHUD', '~> 2.2.5'
	# pod 'NYXImagesKit', '~> 2.3'
	# pod 'MKNetworkKit', '~> 0.87'
	# pod 'WCDB', '~> 1.0.6'
	# pod 'FMDB', '~> 2.7.2'
	# pod 'LBXScan/LBXNative','~> 2.3'
	# pod 'LBXScan/LBXZXing','~> 2.3'
	# pod 'LBXScan/LBXZBar','~> 2.3'
	# pod 'LBXScan/UI','~> 2.3'
	# pod 'TTTAttributedLabel', '~> 2.0.0'
	# pod 'KLCPopup', '~> 1.0'
	# pod 'ActionSheetPicker-3.0', '~> 2.3.0'
	# pod 'CocoaSecurity', '~> 1.2.4'
	# pod 'MXParallaxHeader', '~> 0.6.1'
	# pod 'FCUUID', '~> 1.3.1'
	# pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'
	# pod 'SWTableViewCell', '~> 0.3.7'
	# pod 'DateTools', '~> 2.0.0'
	# pod 'MSWeakTimer', '~> 1.1.0'
	# pod 'iCarousel', '~> 1.8.3'
	# pod 'PNChart', '~> 0.8.9'
	# pod 'NJKWebViewProgress', '~> 0.2.3'
	# pod 'BuglyHotfix', '~> 2.1.0'
	# pod 'HMSegmentedControl', '~> 1.5.3'
	# pod 'CXAlertView', '~> 1.1.0'
	# pod 'FLAnimatedImage', '~> 1.0.12'
	# pod 'SWTableViewCell', '~> 0.3.7'
	# pod 'SLExpandableTableView', '~> 1.3.1'
	# pod 'CMPopTipView', '~> 2.3.0'
	# pod 'SlackTextViewController', '~> 1.9.5'
	# pod 'MJPopupViewController', '~> 0.4'
	# pod 'STPopup', '~> 1.8.3'
	# pod 'CHTwitterCover', '~> 0.1'
	# pod 'APParallaxHeader', '~> 0.1.6'
	# pod 'JDStatusBarNotification', '~> 1.5.3'
	# pod 'MarqueeLabel', '~> 2.7.1'
	# pod 'TLYShyNavBar', '~> 1.0.0'
	# pod 'MXSegmentedPager', '~> 3.3.0'
	# pod 'JHChainableAnimations', '~> 3.0.1'
	# pod 'ZYCornerRadius', '~> 1.0.2'
	# pod 'WXTabBarController', '~> 0.1'
	# pod 'FoldingCell', '~> 3.1.1'
	# pod 'KissXML', '~> 5.2.0'
	# pod 'iVersion', '~> 1.11.5'
	# pod 'MWPhotoBrowser', '~> 2.1.2'
	# pod 'Pgyer', '~> 2.8.9'
	# pod 'PgyUpdate', '~> 1.5'
	# pod 'Bugly', '~> 2.5.0'
	# pod 'UMengUShare/UI’
	# pod 'UMengUShare/Social/WeChat'
	# pod 'UMengUShare/Social/QQ'
	# pod 'Realm', '~> 2.8.3'
	# pod 'JSQMessagesViewController'
	# pod 'AMap3DMap', '~> 5.2.1'
	# pod 'AMapSearch', '~> 5.2.1'
	# pod 'AMapLocation', '~> 2.4.0'
	# pod 'WechatOpenSDK', '~> 1.7.9'
	# pod 'KxMenu', '~> 1'
	# pod 'ChatKit', '~> 0.8.14'
	# pod 'SVWebViewController', '~> 1.0'
	# pod 'Reachability', '~> 3.2'
	# pod 'Bugtags', '~> 2.1.0'
	# pod 'UMengSocial', '~> 5.0'
	# pod 'UMengAnalytics', '~> 3.6.6'
	# pod 'XLForm', '~> 3.3.0'
	# pod 'ZXingObjC', '~> 3.1.0'
	# pod 'MWPhotoBrowser', '~> 2.1.2'
	# pod 'RATreeView', '~> 2.1.1'
	# pod 'PNChart', '~> 0.8.9'
	# pod 'CollapseClick', '~> 1.0.1'
	# pod 'RegexKitLite-NoWarning', '~> 1.1.0'
	# pod 'RegexKitLite', '~> 4.0'
	# pod 'FormatterKit', '~> 1.8.0'
	# pod 'JSPatch', '~> 1.0'
	
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
    end
end

